### ISSUE TITLE
connect electron to rt_server failed wrong version number

### ISSUE THREAD

**Issue by boonkerz** [smasherprog/rat_lite#78] opened 2017-11-14 11:06 UTC
INFO: FILE: /Users/thomas/projekte/Remote_Access_Library/libs/websocket_lite/src/ListenerImpl.cpp Line: 84 Func: operator() Msg: async_handshake failed wrong version number

connect from html client

**Comment by smasherprog** [comment] 2017-11-14 13:33
when debugging connect via ws, not wss

**Comment by boonkerz** [comment] 2017-11-14 13:34
![image](https://user-images.githubusercontent.com/277321/32782515-f8b48bf8-c948-11e7-8a4b-94f8ba29de3e.png)

is ws

**Comment by smasherprog** [comment] 2017-11-14 13:43
I just committed code which will work correctly.
The problem is that release builds force use of TLS, which I havent documented just yet. So, if you pull master it will just work as you would expect.

**Comment by smasherprog** [comment] 2017-11-14 13:52
The last commit should have fixed this issue.
Just note, the only thing I have tested so far is the sending of images. Keyboard, mouse and clipboard have not been tested just yet.

**Closed by smasherprog** 2017-11-14 13:52 UTC
